config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'search', to: 'search#search'
  resources :municipes
  get "up" => "rails/health#show", as: :rails_health_check
  root "municipes#index"
end

app/models/address.rb
class Address < ApplicationRecord  
  validates :neighborhood, :public_place, :state, :city, presence: true
  validates :zip, presence: true, format: { with: /([0-9]{5})-([0-9]{3})/ }
  validates :ibge_code, format: { with: /\A[0-9]{7}\z/ }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  searchkick

  has_one :address
  accepts_nested_attributes_for :address, allow_destroy: true
  after_commit :send_welcome_email, on: :create
  after_commit :send_update_email, on: :update

  enum status: { inactive: 0, active: 1 }
  
  has_one_attached :photo do |attachable|
    attachable.variant :large,  resize_to_fit: [300, 300]
    attachable.variant :medium, resize_to_fit: [160, 160]
    attachable.variant :small,  resize_to_fit: [80, 80]
    attachable.variant :mini,   resize_to_fit: [30, 30]
  end

  validates :name, :birthday, :status, :photo, presence: true
  validates :birthday, not_in_future: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :phone, presence: true,
                    format: { with: /\A\+[0-9]+ [0-9]{2,} [0-9]{5,}-[0-9]{4,}\z/ }

  validates :cns, presence: true,
                  format: { with: /\A[0-9]{15}\z/ }


  private 

  def send_welcome_email
    MunicipeMailer.with(municipe: self).welcome_email.deliver_now
  end
  def send_update_email
    MunicipeMailer.with(municipe: self).update_email.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update ]

  def index
    @municipes = Municipe.all
    @municipe = Municipe.new
  end

  def show
  end

  def new
    @municipe = Municipe.new
    @municipe.build_address
  end

  def edit
  end

  def create
    @municipe = Municipe.new(municipe_params)

    if @municipe.save
      redirect_to root_path, notice: "Municipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @municipe.update(municipe_params)
      redirect_to municipe_url(@municipe), notice: "Municipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  def municipe_params
    params.require(:municipe).permit(:name, :email, :birthday, :phone, :photo, :status, :cns, :cpf, address_attributes:)
  end

  def address_attributes
    [ :neighborhood, :zip, :city, :public_place, :state, :ibge_code ]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search 
    @results = Municipe.search(params[:search])
    @results = Municipe.search("*") if params[:search].blank?

    render turbo_stream:
      turbo_stream.update('municipes',
                           partial: 'municipes/municipe',
                           locals: { municipe: @results })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controle de Municipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto  px-2">
      <%= yield %>
    </main>

  </body>
</html>

app/views/municipes/_form.html.erb
<%= turbo_frame_tag 'new_municipe_component' do %>
  <%= form_for @municipe do |f| %>
    <%= render 'form_content', municipe: @municipe, f: %>
    <%= f.submit "Confirmar", data: {turbo_frame: 'tabela'},  class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <%= link_to 'Voltar', root_path, data: { turbo: :false }, class: "rounded-lg py-3 px-5 bg-red-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  <% end %>
<% end %>

app/views/municipes/_form_content.html.erb
<div x-init="">
  <% if municipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(municipe.errors.count, "erros") %> impediram a criação de municipe.</h2>
      <ul>
        <% municipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class="text-xl py-2 font-medium">Dados</h1>
    <div class="grid grid-cols-2 gap-x-4 gap-y-2 mb-4">
      <div class="">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name, class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                          focus:border-primary-600 block w-full p-2.5" %>
      </div>

      <div class="">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                            focus:border-primary-600 block w-full p-2.5" %>
      </div>

      <div class="">
        <%= f.label :birthday,'Data de nascimento' %>
        <%= f.date_field :birthday, class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
        focus:border-primary-600 block w-full p-2.5" %>
      </div>

      <div class="" >
        <%= f.label :phone, 'Telefone' %>
        <%= f.text_field :phone,"x-mask":"+55 99 99999-9999", class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
        focus:border-primary-600 block w-full p-2.5" %>
      </div>

      <div class="">
        <%= f.label :photo, 'Foto' %>
        <%= f.file_field :photo, class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
        focus:border-primary-600 block w-full p-2.5"  %>
      </div>

      <div class="">
        <%= f.label :status %>
        <div class="mt-2">
          <%= f.select :status, Municipe.statuses.keys.map { |status| [I18n.t("municipe.statuses.#{status}"), status] }, { include_blank: I18n.t("municipe.statuses.select_option") }, class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600" %>
        </div>
      </div>

      <div class="">
        <%= f.label :cns,'CNS' %>
        <%= f.text_field :cns,"x-mask":"999999999999999", class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
        focus:border-primary-600 block w-full p-2.5" %>
      </div>

      <div class="">
        <%= f.label :cpf,'CPF' %>
        <%= f.text_field :cpf,"x-mask":"999.999.999-99", class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
        focus:border-primary-600 block w-full p-2.5" %>
      </div>
    </div>

    <h1 class="text-xl py-2 font-medium">Endereço</h1>
    <%= f.fields_for :address do |address_form| %>
    <div x-data="<%= @municipe.address.to_json %>" class="grid grid-cols-2 gap-x-4 gap-y-2 mb-4">
      <div>
        <%= address_form.label :zip, 'CEP' %>
        <%= address_form.text_field :zip,
                                    "x-mask":"99999-999",
                                    "x-model":"zip",
                                    "@input.debounce.100ms": "getAddress($data, $data.zip)",
                                     class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg
                                            focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                                              %>
      </div>
      <div>
        <%= address_form.label :public_place, 'Rua' %>
        <%= address_form.text_field :public_place,
                                    "x-model":"public_place",
                                    class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                            focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div>
        <%= address_form.label :neighborhood, 'Bairro' %>
        <%= address_form.text_field :neighborhood,
                                    "x-model":"neighborhood",
                                    class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                            focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div>
        <%= address_form.label :city, 'Cidade' %>
        <%= address_form.text_field :city,
                                    "x-model":"city",
                                    class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                            focus:border-primary-600 block w-full p-2.5" %>
      </div>

      <div>
        <%= address_form.label :state, 'Estado' %>
        <%= address_form.text_field :state, 
                                    "x-model":"state",
                                    class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                            focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div>
        <%= address_form.label :ibge_code, 'Código IBGE' %>
        <%= address_form.text_field :ibge_code,"x-mask":"9999999",
                                    "x-model":"ibge_code",
                                    class: "bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600
                                            focus:border-primary-600 block w-full p-2.5" %>
      </div>
    </div>
  <% end %>

app/views/municipes/_municipe.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left rtl:text-right text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="px-12 py-3">
          Nome
        </th>
        <th scope="col" class="px-6 py-3">
          CPF
        </th>
        <th scope="col" class="px-6 py-3">
          Status
        </th>
        <th scope="col" class="px-6 py-3">
        </th>
      </tr>
    </thead>
    <tbody>
      <% municipe.each do |municipe| %>
        <tr id="<%= dom_id municipe %>" class="bg-white border-b dark:border-gray-700">
          <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
            <div class="w-10 h-10 rounded-full">
              <% if municipe.photo.blank? %>
              <%= image_tag("user.png") %>
              <% else %>
                <%= image_tag municipe.photo.variant(:small) %>
              <% end %>
            </div>
            <div class="ps-3">
              <div class="text-base font-semibold"><%= municipe.name %></div>
              <div class="font-normal text-gray-500"><%= municipe.email %></div>
            </div>
          </th>
          <td class="px-6 py-4">
            <%= municipe.cpf %>
          </td>
          <td class="px-6 py-4">
            <div class="flex items-center">
              <% if municipe.status === 'active' %>
                <div class="h-2.5 w-2.5 rounded-full bg-green-500 me-2"></div> Ativo
              <% elsif municipe.status === 'inactive' %>
                <div class="h-2.5 w-2.5 rounded-full bg-red-500 me-2"></div> Inativo
              <% else %>
                <div class="h-2.5 w-2.5 rounded-full bg-gray-500 me-2"></div> Status Desconhecido
              <% end %>
            </div>
          </td>
          <td class="px-6 py-4">
            <%= link_to 'Visualizar', municipe_path(municipe), data: { turbo: :false },  class: "font-medium text-blue-600 hover:underline transition-colors duration-300 ease-in-out" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/municipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 mt-12">
  <h1 class="font-bold text-4xl">Editar munícipe</h1>
  <%= form_for @municipe do |f| %>
    <%= render 'form_content', municipe: @municipe, f: %>
    <%= f.submit "Confirmar", data: { turbo: :false }, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <%= link_to 'Voltar', :back, data: { turbo: :false }, class: "rounded-lg py-3 px-5 bg-red-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

</div>

app/views/municipes/index.html.erb
<div class="w-full">
  <%= turbo_frame_tag 'tabela' do %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Munícipe</h1>
        <div class="flex justify-center m-5">
            <%= link_to "Cadastrar munícipe", new_municipe_path, class: 'btn-modal' , data: { turbo_frame: 'modal' } %>
        </div>
    </div>
    <div class="mb-2">
      <%= turbo_frame_tag "modal" %>
    </div>
    <div class="flex items-center justify-end flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 pb-4 bg-white py-2">
      <%= form_with url: search_path, method: :get do |form| %>
      <%= form.label :search, 'Pesquisar', class:"sr-only" %>
      <div class="relative">
          <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
              <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
              </svg>
          </div>
          <%= form.text_field :search,
                              placeholder: 'Pesquisar munícipes',
                              class: "block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500" %>
      </div>
      <% end %>
    </div>
    <div id="municipes" class="py-2">
      <%= render 'municipes/municipe', municipe: @municipes  %>
    </div>
  <% end %>
</div>

app/views/municipes/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render "form", municipe: @municipe %>
<% end %>

app/views/municipes/show.html.erb
<div class="w-full text-white bg-main-color">
  <div class="container mx-auto my-5 p-5">
      <div class="md:flex no-wrap md:-mx-2 ">
          <div class="w-full md:w-3/12 md:mx-2">
              <div class="bg-white p-3 border-t-4 border-green-400">
                  <div class="image overflow-hidden">
                      <div class="h-auto w-full mx-auto">
                        <% if @municipe.photo.blank? %>
                            <%= image_tag("user.png") %>
                        <% else %>
                            <%= image_tag @municipe.photo %>
                        <% end %>
                      </div>
                  </div>
                  <h1 class="text-gray-900 font-bold text-xl leading-8 my-1"><%= @municipe.name %></h1>
                  <p class="text-sm text-gray-500 hover:text-gray-600 leading-6"><%= @municipe.email %></p>
                  <ul
                      class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
                      <li class="flex items-center py-3">
                        <span>Status</span>
                        <% if @municipe.status === 'active' %>
                        <span class="ml-auto"><span
                                class="bg-green-500 py-1 px-2 rounded text-white text-sm">Ativo</span></span>
                        <% else %>
                          <span class="ml-auto"><span
                          class="bg-red-500 py-1 px-2 rounded text-white text-sm">Inativo</span></span>
                        <% end %>
                      </li>
                      <li class="flex items-center py-3">
                          <span>Data de cadastro</span>
                          <span class="ml-auto"><%= @municipe.created_at.strftime("%d/%m/%Y") %></span>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="w-full md:w-9/12 mx-2 h-64">
              <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="text-black flex justify-end space-x-2">
                  <%= link_to 'Voltar', root_path, class: 'btn-back' %>
                  <%= link_to "Editar", edit_municipe_path(@municipe), class: "btn-edit" %>

                </div>
                  <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                      <span clas="text-green-500">
                          <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                              stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                          </svg>
                      </span>
                      <span class="tracking-wide">Dados</span>
                  </div>
                  <div class="text-gray-700">
                      <div class="grid md:grid-cols-2 text-sm">
                          <div class="grid grid-cols-2">
                              <div class="px-4 py-2 font-semibold">Nome</div>
                              <div class="px-4 py-2"><%= @municipe.name %></div>
                          </div>
                          <div class="grid grid-cols-2">
                              <div class="px-4 py-2 font-semibold">Email</div>
                              <div class="px-4 py-2"><%= @municipe.email %></div>
                          </div>
                          <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Telefone</div>
                            <div class="px-4 py-2"><%= @municipe.phone %></div>
                          </div>
                          <div class="grid grid-cols-2">
                              <div class="px-4 py-2 font-semibold">Cpf</div>
                              <div class="px-4 py-2"><%= @municipe.cpf %></div>
                          </div>
                          <div class="grid grid-cols-2">
                              <div class="px-4 py-2 font-semibold">CNS</div>
                              <div class="px-4 py-2"><%= @municipe.cns %></div>
                          </div>
                          <div class="grid grid-cols-2">
                              <div class="px-4 py-2 font-semibold">Data de nascimento</div>
                              <div class="px-4 py-2"><%= @municipe.birthday.strftime("%d/%m/%Y") %></div>
                          </div>
                      </div>
                  </div>
                  <div class="text-gray-700">
                    <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                      <span clas="text-green-500">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                        </svg>
                        
                      </span>
                      <span class="tracking-wide">Endereço</span>
                  </div>
                    <div class="grid md:grid-cols-2 text-sm">
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Rua</div>
                            <div class="px-4 py-2"><%= @municipe.address.public_place %></div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Bairro</div>
                            <div class="px-4 py-2"><%= @municipe.address.neighborhood %></div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Cidade</div>
                            <div class="px-4 py-2"><%= @municipe.address.city %></div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Estado</div>
                            <div class="px-4 py-2"><%= @municipe.address.state %></div>
                        </div>
                        <div class="grid grid-cols-2">
                          <div class="px-4 py-2 font-semibold">Código IBGE</div>
                          <div class="px-4 py-2"><%= @municipe.address.zip %></div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Código IBGE</div>
                            <div class="px-4 py-2"><%= @municipe.address.ibge_code %></div>
                        </div>
                    </div>
                </div>
              </div>
          </div>
      </div>
  </div>
</div>